config/routes.rb
Rails.application.routes.draw do

  resources :custom_fields
  resources :contacts

  root :to => "contacts#index"

  devise_for :users

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :email, :user

  has_many :contact_fields, dependent: :destroy, inverse_of: :contact

  accepts_nested_attributes_for :contact_fields
end

app/models/contact_field.rb
class ContactField < ActiveRecord::Base
  belongs_to :custom_field
  belongs_to :contact, inverse_of: :contact_fields

  validates_presence_of :value, :custom_field_id
  validates_presence_of :contact

end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base
  belongs_to :user

  enum kind: [:text, :textarea, :combobox]

  validates_presence_of :name, :kind, :user
  # validates_inclusion_of :kind, in: %w(1, 2, 3)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :contacts
  has_many :custom_fields, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @contacts = current_user.contacts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @contact = current_user.contacts.build
    @fields = current_user.custom_fields
    @fields.each do |field|
      @contact.contact_fields.build custom_field: field
    end
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      redirect_to contacts_path, notice: 'Contato cadastrado com sucesso'
    else
      render :new
    end
  end

  def show
    begin
      @contact = current_user.contacts.find(params[:id])
    rescue
      redirect_to root_path, notice: "Você não tem acesso a este contato"
    end
  end


  private

  def contact_params
    params.require(:contact).permit(:name, :email, contact_fields_attributes: [:custom_field_id, :value, :contact_id])
  end
end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @custom_fields = current_user.custom_fields.paginate(page: params[:page], per_page: 10)
  end

  def new
    @custom_field = current_user.custom_fields.build
  end

  def create
    @custom_field = current_user.custom_fields.build(field_params)
    if @custom_field.save
      redirect_to custom_fields_path, notice: "Campo cadastrado com sucesso"
    else
      flash[:notice] = "There's something wrong!"
      render :new
    end
  end
  private

  # TODO: set in before action parse to string if choices was a array
  def field_params
    new_params = params.require(:custom_field).permit(:user_id, :kind, :name, :choices => [])
    new_params[:choices] = new_params[:choices].join(",") if new_params[:choices].present?
    new_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def input_for_kind(kind)
    case kind
    when "textarea"
      :text
    when "text"
      :string
    when "combobox"
      :select
    end
  end


  def input_for_field(form, field)
    unless field.nil?
      if field.kind == "combobox"
        form.input :value, as: :select, collection: field.choices.split(","), label: field.name
      else
        form.input :value, as: input_for_kind(field.kind), label: field.name
      end
    end

  end
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
  <% if @contact.errors.present? %>
    <div class="alert callout" data-closable>

      <p><%= @contact.errors.full_messages %></p>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>

  <% end %>

  <div class="row">
    <div class="large-8 columns">
      <%= f.input :name %>
    </div>
  </div>
  <div class="row">
    <div class="large-8 columns">
      <%= f.input :email %>
    </div>
  </div>
  <%= f.simple_fields_for :contact_fields, @contact.contact_fields do |ff| %>
    <%= ff.input :custom_field_id, as: :hidden, input_html: { value: ff.object.custom_field.id} %>
    <%= input_for_field(ff, ff.object.custom_field) %>
  <% end %>


  <%= f.submit "Save", class: "button" %>
<% end %>

app/views/contacts/index.html.erb
<div class="large-6 large-offset-3 columns">
	<h3>Contacts</h3>
	<p><%= flash[:notice] %></p>
	<table class="hover">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>Options</th>
			</tr>

		</thead>
		<tbody>
			<% @contacts.each do |contact| %>
				<tr>
					<td><%= contact.name %></td>
					<td><%= contact.email %></td>
					<td><%= link_to 'See contact', contact_path(contact) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<div class="row">
		<%= will_paginate @contacts, class: 'custom-pagination columns large-12', previous_label: "<< Anterior", next_label: "Próximo >>" %>
	</div>

	<div class="row">
		<div class="columns large-12">
			<%= link_to "New contact", new_contact_path, class: "button" %>
		</div>
	</div>
</div>

app/views/contacts/new.html.erb
<div class="large-6 large-offset-3 columns">
    <h3>Create new contact</h3>
    <%= render 'form' %>
</div>

app/views/contacts/show.html.erb
<div class="row">
	<h1>Contact #<%= @contact.id%></h1>

	<label class="strong">Name</label>
	<%= @contact.name %>
	<label class="strong">email</label>
	<%= @contact.email %>

	<% @contact.contact_fields.each do |field| %>
		<label class="strong"><%= field.custom_field.name %></label>
		<%= field.value %>
	<% end %>
</div>

<div class="row">
	<%= link_to "back", contacts_path, class: 'button' %>
</div>

app/views/custom_fields/_form.html.erb
<div class="large-12 columns">
  <%= flash[:notice] %>
  <%= simple_form_for @custom_field do |f| %>
    <div class="row">
      <div class="small-12 columns">
        <%= f.input :name, input_html: { class: "large-12 columns" } %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <%= f.input :kind, as: :select, collection: CustomField.kinds.keys, prompt: "Selecione um tipo", input_html: { id: "kind-combobox", class: "large-12 columns" }  %>
      </div>
    </div>

    <div class="row" id="option-wrapper" style="display: none">
      <div class="small-12 columns">
        <fieldset class="option-container">
          <div class="row">
            <legend class="small-12 columns">Options(click in button '+' to add more options and click '-' to remove)</legend>
          </div>
          <div class="row option-field" id="option-1">
            <div class="large-8 columns">
              <div class="row collapse">
                <div class="large-9 columns">
                  <%= text_field_tag 'custom_field[choices][]', "", id: 'text-option-1', placeholder: "Type the new option..." %>
                </div>
                <div class="large-3 columns" id="option-button">
                  <button type="button" class="button postfix add-option">+</button>
                </div>
              </div>
            </div>
          </div>
          <div id="more-options-wrapper">
          </div>
        </fieldset>
      </div>
    </div>


    <%= f.submit 'Save',class: "button", id: "save-button" %>
  <% end %>
</div>

app/views/custom_fields/edit.html.erb
<h3>Edit field</h3>

<%= render 'form' %>

app/views/custom_fields/index.html.erb
<div class="columms large-6 large-offset-3">
  <h3>Fields</h3>

  <p><%= flash[:notice] %></p>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Kind</th>
        <th>Choices</th>
      </tr>
    </thead>
    <tbody>
    <% @custom_fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
        <td><%= field.kind %></td>
        <td><%= field.choices %></td>
      </tr>
    <% end %>
    </tbody>
  </table>


  <div class="row">
	  <%= will_paginate @custom_fields, class: 'custom-pagination columns large-12', previous_label: "<< Anterior", next_label: "Próximo >>" %>
  </div>

  <div class="row">
	  <div class="columns large-12">
		  <%= link_to "New field", new_custom_field_path, class: 'button' %>
	  </div>
  </div>
</div>

app/views/custom_fields/new.html.erb
<div class="columms large-6 large-offset-3">
    <h1>Create new field</h1>
    <%= render 'form' %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="top-bar">
    <div class="top-bar-title">
	
    <strong>Custom Forms</strong>
    </div>
    <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
        </li>
        <li><%= link_to 'Fields', custom_fields_path %></li>
        <li><%= link_to 'Contact', contacts_path %></li>
        <li>
        <a href="#"><%= current_user.email %></a>
        <ul class="menu vertical">
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>
    </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
	<% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
    <% end %>

	<div class="row">
		<%= yield %>
	</div>

  </body>
</html>